# k8s LoadBalancer Service exposing the vulnerable Apache Struts app.
apiVersion: v1
kind: Service
metadata:
  name: apache-struts2-cve-2017-5638
  labels:
    app: apache-struts2-cve-2017-5638
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: apache-struts2-cve-2017-5638
  type: LoadBalancer
---
# The vulnerable Apache Struts app.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-struts2-cve-2017-5638
  labels:
    app: apache-struts2-cve-2017-5638
spec:
  selector:
    matchLabels:
      app: apache-struts2-cve-2017-5638
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apache-struts2-cve-2017-5638
        tier: frontend
    spec:
      containers:
      - name: apache-struts2-cve-2017-5638
        image: piesecurity/apache-struts2-cve-2017-5638
        ports:
        - containerPort: 8080
