apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-h2o-exposed-ui
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: "/flag"
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: h2o-free-secret-provider
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:090c453f05ba740a9903e0932a0394945aa3176ec19dfd7ae34b1fa6930d1b4e
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:2f8c240d2e1734fe8178a5bb2b6d1fb70d370e5da72c3a69e2c79af3f549a885
