# k8s LoadBalancer Service exposing the unprotected Apache Solr service.
apiVersion: v1
kind: Service
metadata:
  name: apache-solr-cve-2019-12409
  labels:
    app: apache-solr-cve-2019-12409
spec:
  ports:
  - protocol: TCP
    port: 18983
    targetPort: 18983
  selector:
    app: apache-solr-cve-2019-12409
  type: LoadBalancer
  # We use a static IP here because we need to explicitly specify the
  # -Djava.rmi.server.hostname option during solr startup.
  # This IP is reserved as a static IP in the tsunami-testbed GCP project.
  loadBalancerIP: 35.197.41.133
---
# The vulnerable Apache Solr service.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-solr-cve-2019-12409
  labels:
    app: apache-solr-cve-2019-12409
spec:
  selector:
    matchLabels:
      app: apache-solr-cve-2019-12409
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apache-solr-cve-2019-12409
        tier: frontend
    spec:
      containers:
      - name: apache-solr-cve-2019-12409
        image: solr:8.2.0
        ports:
        - containerPort: 18983
        env:
        - name: SOLR_OPTS
          value: "-Djava.rmi.server.hostname=35.197.41.133"
