name: roxy-wi-testbed
services:
  roxy-wi:
    image: registry.roxy-wi.org/roxy-wi:7.2.6.0
    command: bash -c 'yum -y install roxy-wi-6-1.0.0.el8 && /usr/sbin/httpd -DFOREGROUND'
    ports:
      - "443:443"
