version: '2'

services:
  tomcat:
    image: docker.io/bitnami/tomcat:10.1
    ports:
      - '8080:8080'
    volumes:
      - 'tomcat_data:/bitnami/tomcat'
    environment:
      - TOMCAT_USERNAME=root
      - TOMCAT_PASSWORD=pass

volumes:
  tomcat_data:
    driver: local