apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-wordpress
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: "/flag"
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: wp-auth-flag-secret-provider
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:c150bab9b0fa425c8d179733f7c61b8ba002edb6c4f7a3f1717a7391fc4d2734
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:da82ba2f3faa946dbdc53ad080b4ad2d87e28172ddef37da5056325ab2e6e338
