# The k8s service exposing the Solr app version 8.2.0 vulnerable to CVE 2919-17558.
apiVersion: v1
kind: Service
metadata:
  name: apache-solr-cve-2019-17558
  labels:
    app: apache-solr-cve-2019-17558
spec:
  ports:
  - port: 8983
  selector:
    app: apache-solr-cve-2019-17558
    tier: frontend
  type: LoadBalancer
---
# Solr app version 8.2.0.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-solr-cve-2019-17558
  labels:
    app: apache-solr-cve-2019-17558
spec:
  selector:
    matchLabels:
      app: apache-solr-cve-2019-17558
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apache-solr-cve-2019-17558
        tier: frontend
    spec:
      containers:
      - image: solr:8.2.0-slim
        name: apache-solr-cve-2019-17558
        command: ["solr-demo"]
        ports:
        - containerPort: 8983
        livenessProbe:
          httpGet:
            path: /solr/
            port: 8983
