# Global config
global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  scrape_timeout: 15s 
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['localhost:9100']
    - targets: ['10.11.5.10:9100']
    - targets: ['10.11.5.11:9100']
    - targets: ['10.11.5.12:9100']
    - targets: ['10.11.5.13:9100']
    - targets: ['10.11.5.14:9100']
    - targets: ['10.11.5.15:9100']
    - targets: ['10.11.5.16:9100']
    - targets: ['10.11.5.17:9100']
    - targets: ['10.11.5.18:9100']
    - targets: ['10.11.5.19:9100']

