apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: drupal-latest-secret-provider
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/internet-ctf/secrets/drupal-latest-root-flag/versions/latest"
        path: "flag-root.txt"
      - resourceName: "projects/internet-ctf/secrets/drupal-latest-exposed-auth-bypass-flag/versions/latest"
        path: "flag-exposed-auth-bypass.txt"
      - resourceName: "projects/internet-ctf/secrets/drupal-latest-password/versions/latest"
        path: "password.txt"