version: '3.5'
services:
  zabbix-server:
    image: docker.m.daocloud.io/zabbix/zabbix-server-mysql:alpine-4.4-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
    ports:
      - "10051:10051"
    depends_on:
      - mysql-server

  zabbix-web:
    image: docker.m.daocloud.io/zabbix/zabbix-web-nginx-mysql:alpine-4.4-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server

  mysql-server:
    image: docker.m.daocloud.io/mysql:5.7
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: