apiVersion: v1
kind: Namespace
metadata:
  name: zabbix

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  namespace: zabbix
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  namespace: zabbix
spec:
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
        - name: mysql-server
          image: mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: "zabbix"
            - name: MYSQL_USER
              value: "zabbix"
            - name: MYSQL_PASSWORD
              value: "zabbix_password"
            - name: MYSQL_ROOT_PASSWORD
              value: "root_password"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: zabbix
spec:
  ports:
    - port: 10051
  selector:
    app: zabbix-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: zabbix
spec:
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-mysql:alpine-4.4.0
          env:
            - name: DB_SERVER_HOST
              value: "mysql-server"
            - name: MYSQL_DATABASE
              value: "zabbix"
            - name: MYSQL_USER
              value: "zabbix"
            - name: MYSQL_PASSWORD
              value: "zabbix_password"
          ports:
            - containerPort: 10051

---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  namespace: zabbix
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 23820
  selector:
    app: zabbix-web
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: zabbix
spec:
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-mysql:alpine-4.4.0
          env:
            - name: DB_SERVER_HOST
              value: "mysql-server"
            - name: MYSQL_DATABASE
              value: "zabbix"
            - name: MYSQL_USER
              value: "zabbix"
            - name: MYSQL_PASSWORD
              value: "zabbix_password"
            - name: ZBX_SERVER_HOST
              value: "zabbix-server"
          ports:
            - containerPort: 80
