version: '3'
x-airflow-common:
  &airflow-common
  image: apache/airflow:1.10.10
  environment:
    &airflow-common-env
    AIRFLOW__WEBSERVER__AUTHENTICATE: 'true'
    AIRFLOW__WEBSERVER__AUTH_BACKEND: 'airflow.contrib.auth.backends.password_auth'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"


services:
  airflow-webserver:
    <<: *airflow-common
    # Installing apache-airflow[password]==1.10.10 to add 
    entrypoint: ["/bin/bash", "-c", "pip install 'apache-airflow[password]==1.10.10' --user && airflow initdb && (airflow webserver & airflow scheduler)"]
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

