apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: challenge-jenkins
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:ab81d07f234180016c419586b2d25eefce24188856e263c1c85c98df5f5cde12
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:66b7add68284ac5b979f2218af74fe4714b1ddac32672d547c88a2ad34d1a15d
