apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-mlflow-cve
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: "/flag"
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: mlflow-cve-secret-provider
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/os
                      operator: In
                      values:
                        - linux
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 50
                preference:
                  matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - three
              - weight: 75
                preference:
                  matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - two
              - weight: 50
                preference:
                  matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - one
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:07d9a706da2e0c2fcd8f45ad51e8a146167897dcb54544ee7651a28a75eb5a4c
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:7148557df927dcc70bb4a3d4df632813f1d3abc0d0e1694d4d0f9545f8b16efe
