apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-h2o
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: "/flag"
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: h2o-exposed-ui-secret-provider
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:92a2981e276205cbb6a76f84a5258a519ceddd3b6e451a635713110f4aff4f86
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:aeb878518706ac9aa4552fbf953ea1dfb1dbd3ba9a90f135785ab251c6fca29a
