---
networks:
  internal:
    driver: bridge
    driver_opts:
        com.docker.network.bridge.enable_ip_masquerade: 'true'
        com.docker.network.bridge.enable_icc: 'true'
    internal: false
    enable_ipv6: true
    ipam:
      config:
        - subnet: "10.11.0.0/16"
        - subnet: "2001:db8:1:1::/64"
volumes:
  root-home:
  home:
  etc-ssh:
  cluster-etc-slurm:
  slurmctld:
  auth:
  src:
  container-shared:
services:
  db:
    image: sql_server:latest
    build:
      context: ./sql_server
      args:
        SUBNET: "10.11"
        SUBNET6: "2001:db8:1:1::"
      network: host
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=slurm
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=slurm_acct_db
      - SUBNET="10.11"
      - SUBNET6="2001:db8:1:1::"
    volumes:
      - /dev/log:/dev/log
    hostname: db

    tty: true
    logging:
      driver: local
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    networks:
      internal:
        ipv4_address: "10.11.1.3"
        ipv6_address: "2001:db8:1:1::1:3"
    extra_hosts:
      - "db:10.11.1.3"
      - "db:2001:db8:1:1::1:3"
      - "slurmdbd:10.11.1.2"
      - "slurmdbd:2001:db8:1:1::1:2"
      - "login:10.11.1.5"
      - "login:2001:db8:1:1::1:5"
      - "rest:10.11.1.6"
      - "rest:2001:db8:1:1::1:6"
      - "proxy:10.11.1.7"
      - "proxy:2001:db8:1:1::1:7"
      - "mgmtnode:10.11.1.1"
      - "mgmtnode:2001:db8:1:1::1:1"

  slurmdbd:
    build:
      context: ./scaleout
      args:
        DOCKER_FROM: almalinux:8
        SLURM_RELEASE: slurm-24.05
        SUBNET: "10.11"
        SUBNET6: "2001:db8:1:1::"
        CACHE_DESTROYER: "e3b0c44298fc1c149afb"
      network: host
    image: scaleout:latest
    environment:
      - SUBNET="10.11"
      - SUBNET6="10.11"
    hostname: slurmdbd
    networks:
      internal:
        ipv4_address: "10.11.1.2"
        ipv6_address: "2001:db8:1:1::1:2"
    volumes:
      - root-home:/root
      - cluster-etc-slurm:/etc/slurm
      - src:/usr/local/src/

      - /dev/log:/dev/log
      - /etc/localtime:/etc/localtime:ro
      - /run/
      - /run/lock/
      - /sys/
      - /sys/fs/cgroup/:/sys/fs/cgroup/:ro
      - /sys/fs/cgroup/docker.slice/:/sys/fs/cgroup/docker.slice/:rw
      - /sys/fs/fuse/:/sys/fs/fuse/:rw
      - /tmp/
      - /var/lib/journal


    tty: true
    logging:
      driver: local
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    depends_on:
      - "db"
    extra_hosts:
      - "db:10.11.1.3"
      - "db:2001:db8:1:1::1:3"
      - "slurmdbd:10.11.1.2"
      - "slurmdbd:2001:db8:1:1::1:2"
      - "login:10.11.1.5"
      - "login:2001:db8:1:1::1:5"
      - "rest:10.11.1.6"
      - "rest:2001:db8:1:1::1:6"
      - "proxy:10.11.1.7"
      - "proxy:2001:db8:1:1::1:7"
      - "mgmtnode:10.11.1.1"
      - "mgmtnode:2001:db8:1:1::1:1"

  mgmtnode:
    image: scaleout:latest
    environment:
      - SUBNET="10.11"
      - SUBNET6="2001:db8:1:1::"
      - container=docker
      - SLURM_FEDERATION_CLUSTER=cluster
    hostname: mgmtnode
    networks:
      internal:
        ipv4_address: 10.11.1.1
        ipv6_address: 2001:db8:1:1::1:1
    volumes:
      - root-home:/root
      - home:/home/
      - slurmctld:/var/spool/slurm
      - etc-ssh:/etc/ssh
      - cluster-etc-slurm:/etc/slurm
      - auth:/auth/
      - src:/usr/local/src/

      - /dev/log:/dev/log
      - /etc/localtime:/etc/localtime:ro
      - /run/
      - /run/lock/
      - /sys/
      - /sys/fs/cgroup/:/sys/fs/cgroup/:ro
      - /sys/fs/cgroup/docker.slice/:/sys/fs/cgroup/docker.slice/:rw
      - /sys/fs/fuse/:/sys/fs/fuse/:rw
      - /tmp/
      - /var/lib/journal



    tty: true
    logging:
      driver: local
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    depends_on:
      - "slurmdbd"
    extra_hosts:
      - "db:10.11.1.3"
      - "db:2001:db8:1:1::1:3"
      - "slurmdbd:10.11.1.2"
      - "slurmdbd:2001:db8:1:1::1:2"
      - "login:10.11.1.5"
      - "login:2001:db8:1:1::1:5"
      - "rest:10.11.1.6"
      - "rest:2001:db8:1:1::1:6"
      - "proxy:10.11.1.7"
      - "proxy:2001:db8:1:1::1:7"
      - "mgmtnode:10.11.1.1"
      - "mgmtnode:2001:db8:1:1::1:1"


  login:
    image: scaleout:latest
    environment:
      - SUBNET="10.11"
      - SUBNET6="2001:db8:1:1::"
      - container=docker
    hostname: login
    networks:
      internal:
        ipv4_address: 10.11.1.5
        ipv6_address: 2001:db8:1:1::1:5
    volumes:
      - root-home:/root
      - etc-ssh:/etc/ssh
      - cluster-etc-slurm:/etc/slurm
      - home:/home/
      - slurmctld:/var/spool/slurm
      - src:/usr/local/src/
      - /var/lib/containers
      - /dev/fuse:/dev/fuse:rw
      - container-shared:/srv/containers

      - /dev/log:/dev/log
      - /etc/localtime:/etc/localtime:ro
      - /run/
      - /run/lock/
      - /sys/
      - /sys/fs/cgroup/:/sys/fs/cgroup/:ro
      - /sys/fs/cgroup/docker.slice/:/sys/fs/cgroup/docker.slice/:rw
      - /sys/fs/fuse/:/sys/fs/fuse/:rw
      - /tmp/
      - /var/lib/journal


    tty: true
    logging:
      driver: local
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    extra_hosts:
      - "db:10.11.1.3"
      - "db:2001:db8:1:1::1:3"
      - "slurmdbd:10.11.1.2"
      - "slurmdbd:2001:db8:1:1::1:2"
      - "login:10.11.1.5"
      - "login:2001:db8:1:1::1:5"
      - "rest:10.11.1.6"
      - "rest:2001:db8:1:1::1:6"
      - "proxy:10.11.1.7"
      - "proxy:2001:db8:1:1::1:7"
      - "mgmtnode:10.11.1.1"
      - "mgmtnode:2001:db8:1:1::1:1"

  node00:
    image: scaleout:latest
    environment:
      - SUBNET="10.11"
      - SUBNET6="2001:db8:1:1::"
      - container=docker
      - SLURM_FEDERATION_CLUSTER=cluster
    hostname: node00
    networks:
      internal:
        ipv4_address: 10.11.5.10
        ipv6_address: 2001:db8:1:1::5:10
    volumes:
      - root-home:/root
      - etc-ssh:/etc/ssh
      - cluster-etc-slurm:/etc/slurm
      - home:/home/
      - src:/usr/local/src/
      - container-shared:/srv/containers

      - /dev/log:/dev/log
      - /etc/localtime:/etc/localtime:ro
      - /run/
      - /run/lock/
      - /sys/
      - /sys/fs/cgroup/:/sys/fs/cgroup/:ro
      - /sys/fs/cgroup/docker.slice/:/sys/fs/cgroup/docker.slice/:rw
      - /sys/fs/fuse/:/sys/fs/fuse/:rw
      - /tmp/
      - /var/lib/journal

    ulimits:
      nproc:
        soft: 65535
        hard: 65535
      nofile:
        soft: 131072
        hard: 131072
      memlock:
        soft: -1
        hard: -1

    tty: true
    logging:
      driver: local
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    depends_on:
      - "mgmtnode"
    extra_hosts:
      - "db:10.11.1.3"
      - "db:2001:db8:1:1::1:3"
      - "slurmdbd:10.11.1.2"
      - "slurmdbd:2001:db8:1:1::1:2"
      - "login:10.11.1.5"
      - "login:2001:db8:1:1::1:5"
      - "rest:10.11.1.6"
      - "rest:2001:db8:1:1::1:6"
      - "proxy:10.11.1.7"
      - "proxy:2001:db8:1:1::1:7"
      - "mgmtnode:10.11.1.1"
      - "mgmtnode:2001:db8:1:1::1:1"


  rest:
    hostname: rest
    name: "scale-out-rest-1"
    image: scaleout:latest
    networks:
      internal:
        ipv4_address: 10.11.1.6
        ipv6_address: 2001:db8:1:1::1:6
    ports:
      - 6820:6820
    volumes:
      - etc-ssh:/etc/ssh
      - cluster-etc-slurm:/etc/slurm

      - /dev/log:/dev/log
      - /etc/localtime:/etc/localtime:ro
      - /run/
      - /run/lock/
      - /sys/
      - /sys/fs/cgroup/:/sys/fs/cgroup/:ro
      - /sys/fs/cgroup/docker.slice/:/sys/fs/cgroup/docker.slice/:rw
      - /sys/fs/fuse/:/sys/fs/fuse/:rw
      - /tmp/
      - /var/lib/journal


    tty: true
    logging:
      driver: local
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - MKNOD
      - SYS_NICE
      - SYS_RESOURCE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    depends_on:
      - "mgmtnode"
    extra_hosts:
      - "db:10.11.1.3"
      - "db:2001:db8:1:1::1:3"
      - "slurmdbd:10.11.1.2"
      - "slurmdbd:2001:db8:1:1::1:2"
      - "login:10.11.1.5"
      - "login:2001:db8:1:1::1:5"
      - "rest:10.11.1.6"
      - "rest:2001:db8:1:1::1:6"
      - "proxy:10.11.1.7"
      - "proxy:2001:db8:1:1::1:7"
      - "mgmtnode:10.11.1.1"
      - "mgmtnode:2001:db8:1:1::1:1"



