apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-prometheus
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: "/chroot/flag"
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: prometheus-secret-provider
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/os
                      operator: In
                      values:
                        - linux
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 50
                preference:
                  matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - three
              - weight: 75
                preference:
                  matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - two
              - weight: 50
                preference:
                  matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - one
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:3c6cd243c7290b683296e7c09bd1ecea4aa5c2766dd3a4d9a494498c49fc4b1b
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:241f4b246963ce4d0c9a0f47e49facd77f312c9932e0f0ceaac8a0e5b125f9d7
