# k8s LoadBalancer Service exposing an Apache httpd instance with SSRF exploitable mod_proxy.
apiVersion: v1
kind: Service
metadata:
  name: apache-mod-proxy-cve-2021-40438
  labels:
    app: apache-mod-proxy-cve-2021-40438
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: apache-mod-proxy-cve-2021-40438
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-mod-proxy-cve-2021-40438
  labels:
    app: apache-mod-proxy-cve-2021-40438
spec:
  selector:
    matchLabels:
      app: apache-mod-proxy-cve-2021-40438
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apache-mod-proxy-cve-2021-40438
        tier: frontend
    spec:
      containers:
      - name: apache-mod-proxy-cve-2021-40438
        image: ${mod_proxy_img}
        ports:
        - containerPort: 80
