apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-nodered
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - port: 1337
        protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: "/chroot/flag"
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: nodered-secret-provider
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/os
                      operator: In
                      values:
                        - linux
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 50
                preference:
                  matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - three
              - weight: 75
                preference:
                  matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - two
              - weight: 50
                preference:
                  matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - one
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:3375dc85ec59311dcc4b416ba9aab50af651bf63df9e7b1c0c8344b5edc23e06
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:22f16c86718240423ca0d3423bb5d40279a1e5e5edfbfbb9d463822b457fef1d
