version: '3.8'

services:
  nexus:
    image: sonatype/nexus3:3.68.0-java11
    container_name: nexus
    ports:
      - "8081:8081"
    restart: unless-stopped
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data:
