apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tomcat-ghostcat-provider
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/internet-ctf/secrets/tomcat-ghostcat-flag/versions/latest"
        path: "flag.txt"
