apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-bento
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: "/chroot/flag"
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: bento-secret-provider
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:d610fcf30d926dba7751f7f28d6a86eece9793d880f1a7166922364b787ba0ff
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:6c62fd73b3603ef2a3d519d49f02a9d90c5d5b6612465784cc2e5fc316829c01
