# k8s LoadBalancer Service exposing the vulnerable PHP app.
apiVersion: v1
kind: Service
metadata:
  name: phpunit-cve-2017-9841
  labels:
    app: phpunit-cve-2017-9841
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: phpunit-cve-2017-9841
  type: LoadBalancer
---
# The PHP app.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpunit-cve-2017-9841
  labels:
    app: phpunit-cve-2017-9841
spec:
  selector:
    matchLabels:
      app: phpunit-cve-2017-9841
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpunit-cve-2017-9841
        tier: frontend
    spec:
      containers:
      - name: phpunit-cve-2017-9841
        image: ${phpunit_img}
        ports:
        - containerPort: 80
