apisix:
  node_listen: 9080
  enable_ipv6: false
  allow_admin:
    - 0.0.0.0/0
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092
etcd:
  host:
    - "http://etcd:2379"
  prefix: "/apisix"
  timeout: 30
