apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-apache
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: /chroot/flag
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: apache-path-traversal-secret-provider
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/os
                      operator: In
                      values:
                        - linux
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 50
                preference:
                  matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - two
              - weight: 50
                preference:
                  matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - one
              - weight: 75
                preference:
                  matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - three
  healthcheck:
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:5d924e76ed3a6ccee5f2d5ce3914d2b602a5817343328e16f7832c61474bc247
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:363b76206162ad927e63719d9d5a5a52493b0c306a58a1266564d8044c2ee0c1
