apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-grafana
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - port: 1337
        protocol: "TCP"
        targetPort: 1337
  podTemplate:
    template:
      spec:
        #        securityContext:
        #          sysctls:
        #            - name: "net.ipv4.ip_unprivileged_port_start"
        #              value: "0"
        containers:
          - name: challenge
            volumeMounts:
              - name: flag-volume
                mountPath: "/flag"
        serviceAccountName: secret-readonly-sa
        volumes:
          - name: flag-volume
            csi:
              driver: secrets-store-gke.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: grafana-secret-provider
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/os
                      operator: In
                      values:
                        - linux
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 50
                preference:
                  matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - three
              - weight: 75
                preference:
                  matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - two
              - weight: 50
                preference:
                  matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - one
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/internet-ctf/challenges/healthcheck:de4a5ffbc736e71501c5f260d1f2840603a8f4db4c87c84d8e948ac244f83944
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:e7410354f61229e710097a998a0deaf899be0ae0464b5d5e987931e75a58e458
