# k8s LoadBalancer Service
apiVersion: v1
kind: Service
metadata:
  name: drupal-cve-2018-7600
  labels:
    app: drupal-cve-2018-7600
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: drupal-cve-2018-7600
  type: LoadBalancer
---
# The PHP app.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-cve-2018-7600
  labels:
    app: drupal-cve-2018-7600
spec:
  selector:
    matchLabels:
      app: drupal-cve-2018-7600
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal-cve-2018-7600
        tier: frontend
    spec:
      containers:
      - name: drupal-cve-2018-7600
        image: drupal:${drupal_version}
        ports:
        - containerPort: 80
