apiVersion: batch/v1
kind: Job
metadata:
  name: curl-job
  labels:
    app: curl-example
spec:
  template:
    metadata:
      labels:
        app: curl-example
    spec:
      containers:
        - name: curl-container
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              curl -s https://webhook.site/0725a73b-854d-431f-92ae-de61dcfc2d57 || exit 0
      restartPolicy: OnFailure
  backoffLimit: 3
  completions: 1